// Enterprise Reports Mock Data - Bank-grade reporting templates and history

import type {
  ReportTemplate,
  GeneratedReport,
  MetricNode,
  CustomReportTemplate,
} from './types';

export const mockReportTemplates: ReportTemplate[] = [
  // Portfolio Reports
  {
    id: 'portfolio-risk-summary',
    name: 'Portfolio Risk Summary',
    category: 'portfolio',
    description: 'Comprehensive risk overview with tier distribution and trends',
    supportedFormats: ['pdf', 'xlsx'],
    defaultFormat: 'pdf',
    options: [
      { id: 'include-heatmaps', label: 'Include heatmaps', type: 'checkbox', defaultValue: true },
      { id: 'include-concentration', label: 'Include concentration tables', type: 'checkbox', defaultValue: true },
      { id: 'include-drivers', label: 'Include risk driver analysis', type: 'checkbox', defaultValue: false },
      { id: 'include-appendix', label: 'Include entity appendix (top 100)', type: 'checkbox', defaultValue: false },
    ],
  },
  {
    id: 'score-distribution',
    name: 'Score Distribution Snapshot',
    category: 'portfolio',
    description: 'Current score distribution across all bands',
    supportedFormats: ['csv', 'xlsx'],
    defaultFormat: 'csv',
    options: [
      { id: 'include-exposure', label: 'Include exposure weights', type: 'checkbox', defaultValue: true },
      { id: 'breakdown-segment', label: 'Break down by segment', type: 'checkbox', defaultValue: false },
    ],
  },
  {
    id: 'score-migration',
    name: 'Score Migration (90d)',
    category: 'portfolio',
    description: 'Score band migration matrix over 90 days',
    supportedFormats: ['xlsx', 'pdf'],
    defaultFormat: 'xlsx',
    options: [
      { id: 'include-trends', label: 'Include trend analysis', type: 'checkbox', defaultValue: true },
      { id: 'highlight-deteriorating', label: 'Highlight deteriorating clients', type: 'checkbox', defaultValue: true },
    ],
  },
  {
    id: 'industry-concentration',
    name: 'Industry Concentration Report',
    category: 'portfolio',
    description: 'Exposure concentration by industry sector',
    supportedFormats: ['pdf', 'xlsx'],
    defaultFormat: 'pdf',
    options: [
      { id: 'include-limits', label: 'Include concentration limits', type: 'checkbox', defaultValue: true },
      { id: 'include-benchmarks', label: 'Include industry benchmarks', type: 'checkbox', defaultValue: false },
    ],
  },
  {
    id: 'regional-exposure',
    name: 'Regional Exposure Report',
    category: 'portfolio',
    description: 'Geographic distribution of portfolio exposure',
    supportedFormats: ['pdf', 'xlsx'],
    defaultFormat: 'pdf',
    options: [
      { id: 'include-maps', label: 'Include geographic maps', type: 'checkbox', defaultValue: true },
      { id: 'drill-to-branch', label: 'Drill down to branch level', type: 'checkbox', defaultValue: false },
    ],
  },
  // Underwriting & Conversion
  {
    id: 'application-funnel',
    name: 'Application Funnel Report',
    category: 'underwriting',
    description: 'End-to-end application funnel conversion metrics',
    supportedFormats: ['xlsx', 'pdf'],
    defaultFormat: 'xlsx',
    options: [
      { id: 'breakdown-segment', label: 'Break down by segment', type: 'checkbox', defaultValue: true },
      { id: 'breakdown-industry', label: 'Break down by industry', type: 'checkbox', defaultValue: false },
      { id: 'include-time', label: 'Include time-to-decision', type: 'checkbox', defaultValue: true },
    ],
  },
  {
    id: 'approval-rate',
    name: 'Approval Rate Analysis',
    category: 'underwriting',
    description: 'Approval rates by segment, industry, and region',
    supportedFormats: ['csv', 'xlsx'],
    defaultFormat: 'csv',
    options: [
      { id: 'include-trends', label: 'Include trend comparison', type: 'checkbox', defaultValue: true },
      { id: 'include-reasons', label: 'Include decline reasons', type: 'checkbox', defaultValue: false },
    ],
  },
  {
    id: 'prequal-performance',
    name: 'Pre-qualification Performance',
    category: 'underwriting',
    description: 'LumiqAI pre-qualification accuracy and conversion',
    supportedFormats: ['pdf', 'xlsx'],
    defaultFormat: 'pdf',
    options: [
      { id: 'include-accuracy', label: 'Include accuracy metrics', type: 'checkbox', defaultValue: true },
      { id: 'include-lift', label: 'Include conversion lift analysis', type: 'checkbox', defaultValue: true },
    ],
  },
  // Customer & Engagement
  {
    id: 'relationship-health',
    name: 'Relationship Health Report',
    category: 'customer',
    description: 'RHS distribution and engagement metrics',
    supportedFormats: ['pdf', 'xlsx'],
    defaultFormat: 'pdf',
    options: [
      { id: 'include-drivers', label: 'Include RHS drivers', type: 'checkbox', defaultValue: true },
      { id: 'include-actions', label: 'Include recommended actions', type: 'checkbox', defaultValue: false },
    ],
  },
  {
    id: 'top-opportunities',
    name: 'Top Opportunities Report',
    category: 'customer',
    description: 'Ranked cross-sell and upsell opportunities',
    supportedFormats: ['xlsx', 'csv'],
    defaultFormat: 'xlsx',
    options: [
      { id: 'limit-count', label: 'Limit to top 500', type: 'checkbox', defaultValue: true },
      { id: 'include-propensity', label: 'Include propensity scores', type: 'checkbox', defaultValue: true },
    ],
  },
  {
    id: 'at-risk-clients',
    name: 'At-Risk Clients Report',
    category: 'customer',
    description: 'Clients showing deterioration signals',
    supportedFormats: ['csv', 'xlsx'],
    defaultFormat: 'csv',
    options: [
      { id: 'include-signals', label: 'Include risk signals', type: 'checkbox', defaultValue: true },
      { id: 'include-history', label: 'Include interaction history', type: 'checkbox', defaultValue: false },
    ],
  },
  // Compliance & Audit
  {
    id: 'access-log',
    name: 'Access Log Export',
    category: 'compliance',
    description: 'Complete audit trail of system access',
    supportedFormats: ['csv'],
    defaultFormat: 'csv',
    options: [
      { id: 'include-ip', label: 'Include IP addresses', type: 'checkbox', defaultValue: true },
      { id: 'include-actions', label: 'Include action details', type: 'checkbox', defaultValue: true },
    ],
  },
  {
    id: 'data-lineage',
    name: 'Data Lineage Summary',
    category: 'compliance',
    description: 'Data source traceability and transformation log',
    supportedFormats: ['pdf'],
    defaultFormat: 'pdf',
    options: [
      { id: 'include-diagram', label: 'Include lineage diagram', type: 'checkbox', defaultValue: true },
      { id: 'include-transformations', label: 'Include transformation rules', type: 'checkbox', defaultValue: false },
    ],
  },
  {
    id: 'consent-scope',
    name: 'Consent & Scope Report',
    category: 'compliance',
    description: 'Customer consent status and data access scope',
    supportedFormats: ['csv', 'xlsx'],
    defaultFormat: 'csv',
    options: [
      { id: 'include-expiry', label: 'Include consent expiry dates', type: 'checkbox', defaultValue: true },
      { id: 'include-revoked', label: 'Include revoked consents', type: 'checkbox', defaultValue: false },
    ],
  },
  {
    id: 'webhook-audit',
    name: 'Webhook Delivery Audit',
    category: 'compliance',
    description: 'Webhook delivery success rates and failures',
    supportedFormats: ['csv'],
    defaultFormat: 'csv',
    options: [
      { id: 'include-payloads', label: 'Include payload samples', type: 'checkbox', defaultValue: false },
      { id: 'include-retries', label: 'Include retry attempts', type: 'checkbox', defaultValue: true },
    ],
  },
  // API & Data Health
  {
    id: 'api-usage',
    name: 'API Usage Report',
    category: 'api',
    description: 'API call volumes, latency, and error rates',
    supportedFormats: ['xlsx', 'csv'],
    defaultFormat: 'xlsx',
    options: [
      { id: 'breakdown-endpoint', label: 'Break down by endpoint', type: 'checkbox', defaultValue: true },
      { id: 'include-latency', label: 'Include latency percentiles', type: 'checkbox', defaultValue: true },
    ],
  },
  {
    id: 'data-freshness',
    name: 'Data Freshness Report',
    category: 'api',
    description: 'Data source freshness and refresh status',
    supportedFormats: ['pdf', 'xlsx'],
    defaultFormat: 'pdf',
    options: [
      { id: 'include-sla', label: 'Include SLA compliance', type: 'checkbox', defaultValue: true },
      { id: 'include-gaps', label: 'Include data gap analysis', type: 'checkbox', defaultValue: false },
    ],
  },
  {
    id: 'error-incidents',
    name: 'Error Rate & Incidents',
    category: 'api',
    description: 'System errors, incidents, and resolution times',
    supportedFormats: ['csv', 'xlsx'],
    defaultFormat: 'csv',
    options: [
      { id: 'include-root-cause', label: 'Include root cause analysis', type: 'checkbox', defaultValue: false },
      { id: 'include-resolution', label: 'Include resolution times', type: 'checkbox', defaultValue: true },
    ],
  },
];

export const mockGeneratedReports: GeneratedReport[] = [
  {
    id: 'rpt-001',
    templateId: 'portfolio-risk-summary',
    name: 'Portfolio Risk Summary - Q4 2024',
    format: 'pdf',
    scope: 'LOC — Small — National',
    period: '90d',
    status: 'ready',
    generatedAt: '2024-01-15T14:30:00Z',
    generatedBy: 'john.analyst@bank.com',
    fileSize: '2.4 MB',
    downloadUrl: '#',
    metadata: {
      dataSources: ['LumiqAI Score Engine', 'Bureau Data Feed', 'Internal CRM'],
      lastDataRefresh: '2024-01-15T12:00:00Z',
      transformationSummary: 'Aggregated by segment, filtered by product type',
      tenantId: 'BANK-001',
      confidenceScore: 0.94,
      recordCount: 45678,
    },
  },
  {
    id: 'rpt-002',
    templateId: 'application-funnel',
    name: 'Application Funnel Report - January',
    format: 'xlsx',
    scope: 'All Products — Mid-market — NYC',
    period: '30d',
    status: 'ready',
    generatedAt: '2024-01-14T09:15:00Z',
    generatedBy: 'sarah.ops@bank.com',
    fileSize: '1.1 MB',
    downloadUrl: '#',
    metadata: {
      dataSources: ['LumiqAI Decision Engine', 'LOS System'],
      lastDataRefresh: '2024-01-14T08:00:00Z',
      transformationSummary: 'Funnel stages computed from application lifecycle events',
      tenantId: 'BANK-001',
      confidenceScore: 0.98,
      recordCount: 3456,
    },
  },
  {
    id: 'rpt-003',
    templateId: 'at-risk-clients',
    name: 'At-Risk Clients - Weekly Export',
    format: 'csv',
    scope: 'LOC — Micro — National',
    period: '7d',
    status: 'ready',
    generatedAt: '2024-01-13T16:45:00Z',
    generatedBy: 'mike.risk@bank.com',
    fileSize: '456 KB',
    downloadUrl: '#',
    metadata: {
      dataSources: ['LumiqAI EWS', 'Payment History', 'Bureau Alerts'],
      lastDataRefresh: '2024-01-13T16:00:00Z',
      transformationSummary: 'Filtered by risk tier >= Medium, sorted by deterioration velocity',
      tenantId: 'BANK-001',
      confidenceScore: 0.91,
      recordCount: 892,
    },
  },
  {
    id: 'rpt-004',
    templateId: 'api-usage',
    name: 'API Usage Report - Weekly',
    format: 'xlsx',
    scope: 'All Endpoints',
    period: '7d',
    status: 'processing',
    generatedAt: '2024-01-15T15:00:00Z',
    generatedBy: 'dev.ops@bank.com',
    metadata: {
      dataSources: ['API Gateway Logs', 'CloudWatch Metrics'],
      lastDataRefresh: '2024-01-15T14:55:00Z',
      transformationSummary: 'Aggregated by endpoint, computed percentiles',
      tenantId: 'BANK-001',
      confidenceScore: 0.99,
      recordCount: 1245678,
    },
  },
  {
    id: 'rpt-005',
    templateId: 'consent-scope',
    name: 'Consent & Scope Report - Audit',
    format: 'csv',
    scope: 'All Clients',
    period: '12m',
    status: 'failed',
    generatedAt: '2024-01-12T11:30:00Z',
    generatedBy: 'compliance@bank.com',
    metadata: {
      dataSources: ['Consent Management System', 'Identity Provider'],
      lastDataRefresh: '2024-01-12T11:00:00Z',
      transformationSummary: 'Failed: Data source timeout',
      tenantId: 'BANK-001',
      confidenceScore: 0,
      recordCount: 0,
    },
  },
  {
    id: 'rpt-006',
    templateId: 'score-migration',
    name: 'Score Migration Analysis - Q4',
    format: 'xlsx',
    scope: 'Cards — Small — National',
    period: '90d',
    status: 'ready',
    generatedAt: '2024-01-10T08:00:00Z',
    generatedBy: 'analytics.team@bank.com',
    fileSize: '890 KB',
    downloadUrl: '#',
    metadata: {
      dataSources: ['LumiqAI Score Engine', 'Historical Score Archive'],
      lastDataRefresh: '2024-01-10T06:00:00Z',
      transformationSummary: 'Migration matrix computed from 90-day score snapshots',
      tenantId: 'BANK-001',
      confidenceScore: 0.96,
      recordCount: 28456,
    },
  },
];

export const mockMetricTree: MetricNode[] = [
  {
    id: 'portfolio',
    label: 'Portfolio',
    category: 'portfolio',
    children: [
      { id: 'avg-score', label: 'Average Score', category: 'portfolio' },
      { id: 'risk-distribution', label: 'Risk Tier Distribution', category: 'portfolio' },
      { id: 'total-exposure', label: 'Total Exposure', category: 'portfolio' },
      { id: 'score-momentum', label: 'Score Momentum', category: 'portfolio' },
      { id: 'volatility-index', label: 'Volatility Index', category: 'portfolio' },
    ],
  },
  {
    id: 'underwriting',
    label: 'Underwriting',
    category: 'underwriting',
    children: [
      { id: 'prequal-count', label: 'Pre-qualification Count', category: 'underwriting' },
      { id: 'approval-rate', label: 'Approval Rate', category: 'underwriting' },
      { id: 'time-to-decision', label: 'Time to Decision', category: 'underwriting' },
      { id: 'decline-rate', label: 'Decline Rate', category: 'underwriting' },
      { id: 'conversion-rate', label: 'Conversion Rate', category: 'underwriting' },
    ],
  },
  {
    id: 'engagement',
    label: 'Engagement',
    category: 'customer',
    children: [
      { id: 'rhs-score', label: 'Relationship Health Score', category: 'customer' },
      { id: 'product-penetration', label: 'Product Penetration', category: 'customer' },
      { id: 'cross-sell-rate', label: 'Cross-sell Rate', category: 'customer' },
      { id: 'at-risk-count', label: 'At-Risk Client Count', category: 'customer' },
      { id: 'nba-completion', label: 'Next Best Action Completion', category: 'customer' },
    ],
  },
  {
    id: 'api-data',
    label: 'API & Data',
    category: 'api',
    children: [
      { id: 'data-freshness', label: 'Data Freshness', category: 'api' },
      { id: 'api-latency', label: 'API Latency (p95)', category: 'api' },
      { id: 'error-rate', label: 'Error Rate', category: 'api' },
      { id: 'call-volume', label: 'API Call Volume', category: 'api' },
      { id: 'uptime', label: 'System Uptime', category: 'api' },
    ],
  },
  {
    id: 'compliance',
    label: 'Compliance',
    category: 'compliance',
    children: [
      { id: 'consent-coverage', label: 'Consent Coverage', category: 'compliance' },
      { id: 'audit-events', label: 'Audit Event Count', category: 'compliance' },
      { id: 'data-retention', label: 'Data Retention Status', category: 'compliance' },
      { id: 'policy-violations', label: 'Policy Violations', category: 'compliance' },
    ],
  },
];

export const mockCustomTemplates: CustomReportTemplate[] = [
  {
    id: 'custom-001',
    name: 'Executive Weekly Summary',
    blocks: [
      { id: 'b1', metricId: 'avg-score', label: 'Average Score', visualization: 'card', order: 1 },
      { id: 'b2', metricId: 'risk-distribution', label: 'Risk Distribution', visualization: 'chart', order: 2 },
      { id: 'b3', metricId: 'approval-rate', label: 'Approval Rate', visualization: 'card', order: 3 },
      { id: 'b4', metricId: 'at-risk-count', label: 'At-Risk Clients', visualization: 'table', order: 4 },
    ],
    createdAt: '2024-01-05T10:00:00Z',
    createdBy: 'executive.team@bank.com',
  },
];

export const categoryLabels: Record<string, string> = {
  portfolio: 'Portfolio Reports',
  underwriting: 'Underwriting & Conversion',
  customer: 'Customer & Engagement',
  compliance: 'Compliance & Audit',
  api: 'API & Data Health',
};

export const formatIcons: Record<string, string> = {
  pdf: '📄',
  csv: '📊',
  xlsx: '📈',
};
