// Enterprise Report Preview Drawer - Side panel for report preview and metadata

import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  X, 
  Download, 
  Share2, 
  Cloud, 
  FileText, 
  FileSpreadsheet, 
  Table,
  Clock,
  Database,
  Shield,
  BarChart3,
  
  CheckCircle2
} from 'lucide-react';
import type { GeneratedReport } from './types';

interface ReportPreviewDrawerProps {
  report: GeneratedReport | null;
  isOpen: boolean;
  onClose: () => void;
  onDownload: (report: GeneratedReport) => void;
}

const FormatIcon: React.FC<{ format: string }> = ({ format }) => {
  switch (format) {
    case 'pdf':
      return <FileText className="h-5 w-5 text-red-500" />;
    case 'xlsx':
      return <FileSpreadsheet className="h-5 w-5 text-green-600" />;
    case 'csv':
      return <Table className="h-5 w-5 text-blue-500" />;
    default:
      return <FileText className="h-5 w-5 text-muted-foreground" />;
  }
};

const formatDate = (dateString: string): string => {
  const date = new Date(dateString);
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
};

export const ReportPreviewDrawer: React.FC<ReportPreviewDrawerProps> = ({
  report,
  isOpen,
  onClose,
  onDownload,
}) => {
  return (
    <AnimatePresence>
      {isOpen && report && (
        <>
          {/* Backdrop */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-background/80 backdrop-blur-sm z-40"
            onClick={onClose}
          />

          {/* Drawer */}
          <motion.div
            initial={{ x: '100%' }}
            animate={{ x: 0 }}
            exit={{ x: '100%' }}
            transition={{ type: 'spring', damping: 25, stiffness: 200 }}
            className="fixed right-0 top-0 h-full w-full max-w-lg bg-card border-l border-border shadow-xl z-50 flex flex-col"
          >
            {/* Header */}
            <div className="p-4 border-b border-border flex items-start justify-between">
              <div className="flex items-start gap-3">
                <FormatIcon format={report.format} />
                <div>
                  <h2 className="text-lg font-semibold text-foreground">{report.name}</h2>
                  <div className="flex items-center gap-2 mt-1">
                    <span className="px-2 py-0.5 bg-muted rounded text-xs font-medium uppercase">
                      {report.format}
                    </span>
                    {report.fileSize && (
                      <span className="text-xs text-muted-foreground">{report.fileSize}</span>
                    )}
                  </div>
                </div>
              </div>
              <button
                onClick={onClose}
                className="p-2 hover:bg-muted rounded-md transition-colors"
              >
                <X className="h-5 w-5 text-muted-foreground" />
              </button>
            </div>

            {/* Content */}
            <div className="flex-1 overflow-y-auto p-4 space-y-6">
              {/* Generation Info */}
              <div className="space-y-3">
                <h3 className="text-sm font-medium text-foreground flex items-center gap-2">
                  <Clock className="h-4 w-4 text-muted-foreground" />
                  Generation Details
                </h3>
                <div className="bg-muted/50 rounded-lg p-3 space-y-2 text-sm">
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">Generated</span>
                    <span className="font-medium">{formatDate(report.generatedAt)}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">Generated by</span>
                    <span className="font-medium">{report.generatedBy}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">Scope</span>
                    <span className="font-medium">{report.scope}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">Period</span>
                    <span className="font-medium">{report.period}</span>
                  </div>
                </div>
              </div>

              {/* Data Sources */}
              <div className="space-y-3">
                <h3 className="text-sm font-medium text-foreground flex items-center gap-2">
                  <Database className="h-4 w-4 text-muted-foreground" />
                  Data Sources
                </h3>
                <div className="space-y-2">
                  {report.metadata.dataSources.map((source, idx) => (
                    <div
                      key={idx}
                      className="flex items-center gap-2 p-2 bg-muted/50 rounded-md text-sm"
                    >
                      <CheckCircle2 className="h-4 w-4 text-green-500" />
                      <span>{source}</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Metadata */}
              <div className="space-y-3">
                <h3 className="text-sm font-medium text-foreground flex items-center gap-2">
                  <Shield className="h-4 w-4 text-muted-foreground" />
                  Governance Metadata
                </h3>
                <div className="bg-muted/50 rounded-lg p-3 space-y-2 text-sm">
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">Last Data Refresh</span>
                    <span className="font-medium">{formatDate(report.metadata.lastDataRefresh)}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">Tenant ID</span>
                    <span className="font-medium font-mono text-xs">{report.metadata.tenantId}</span>
                  </div>
                  <div className="flex justify-between items-center">
                    <span className="text-muted-foreground">Confidence Score</span>
                    <div className="flex items-center gap-2">
                      <div className="w-20 h-2 bg-muted rounded-full overflow-hidden">
                        <div 
                          className="h-full bg-green-500 rounded-full" 
                          style={{ width: `${report.metadata.confidenceScore * 100}%` }}
                        />
                      </div>
                      <span className="font-medium">{(report.metadata.confidenceScore * 100).toFixed(0)}%</span>
                    </div>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">Record Count</span>
                    <span className="font-medium">{report.metadata.recordCount.toLocaleString()}</span>
                  </div>
                </div>
              </div>

              {/* Transformation Summary */}
              <div className="space-y-3">
                <h3 className="text-sm font-medium text-foreground flex items-center gap-2">
                  <BarChart3 className="h-4 w-4 text-muted-foreground" />
                  Transformation Summary
                </h3>
                <p className="text-sm text-muted-foreground bg-muted/50 rounded-lg p-3">
                  {report.metadata.transformationSummary}
                </p>
              </div>

              {/* Preview Placeholder */}
              <div className="space-y-3">
                <h3 className="text-sm font-medium text-foreground">Content Preview</h3>
                <div className="border border-dashed border-border rounded-lg p-8 flex items-center justify-center bg-muted/30">
                  <div className="text-center">
                    <FormatIcon format={report.format} />
                    <p className="text-sm text-muted-foreground mt-2">
                      {report.format === 'pdf' 
                        ? 'PDF preview available upon download' 
                        : `First 50 rows of ${report.format.toUpperCase()} data`}
                    </p>
                  </div>
                </div>
              </div>
            </div>

            {/* Actions */}
            <div className="p-4 border-t border-border space-y-2">
              <button
                onClick={() => onDownload(report)}
                className="w-full flex items-center justify-center gap-2 h-11 bg-primary text-primary-foreground rounded-md font-medium hover:bg-primary/90 transition-colors"
              >
                <Download className="h-4 w-4" />
                Download Report
              </button>
              <div className="flex gap-2">
                <button className="flex-1 flex items-center justify-center gap-2 h-10 border border-border rounded-md text-sm font-medium hover:bg-muted transition-colors">
                  <Share2 className="h-4 w-4" />
                  Share Internally
                </button>
                <button className="flex-1 flex items-center justify-center gap-2 h-10 border border-border rounded-md text-sm font-medium hover:bg-muted transition-colors">
                  <Cloud className="h-4 w-4" />
                  Export to S3
                </button>
              </div>
            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
};

export default ReportPreviewDrawer;
